name: backend
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  mountain_models:
    path: packages/mountain_models
  posts_data_source:
    path: packages/posts_data_source
  in_memory_users_data_source:
    path: packages/in_memory_users_data_source
  in_memory_posts_data_source:
    path: packages/in_memory_posts_data_source
  users_data_source:
    path: packages/users_data_source
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  http: ^1.0.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
